// @flowIgnore
// NOTE: THIS FILE IS AUTO-GENERATED. MANUAL CHANGES OF THIS FILE WILL BE LOST!

import callToAction1 from "./callToAction1";
import callToAction2 from "./callToAction2";
import callToAction3 from "./callToAction3";
import callToAction4 from "./callToAction4";
import callToAction5 from "./callToAction5";
import callToAction11 from "./callToAction11";
import callToAction6 from "./callToAction6";
import callToAction7 from "./callToAction7";
import callToAction8 from "./callToAction8";
import callToAction9 from "./callToAction9";
import callToAction10 from "./callToAction10";
import content2 from "./content2";
import content3 from "./content3";
import content4 from "./content4";
import content5 from "./content5";
import content6 from "./content6";
import content7 from "./content7";
import content8 from "./content8";
import content9 from "./content9";
import content10 from "./content10";
import content1 from "./content1";
import content11 from "./content11";
import content12 from "./content12";
import content13 from "./content13";
import content14 from "./content14";
import content15 from "./content15";
import feature1 from "./feature1";
import feature2 from "./feature2";
import feature3 from "./feature3";
import feature4 from "./feature4";
import feature5 from "./feature5";
import feature6 from "./feature6";
import feature7 from "./feature7";
import feature8 from "./feature8";
import feature9 from "./feature9";
import feature10 from "./feature10";
import feature11 from "./feature11";
import feature12 from "./feature12";
import feature13 from "./feature13";
import feature14 from "./feature14";
import header1 from "./header1";
import header2 from "./header2";
import header3 from "./header3";
import header4 from "./header4";
import header5 from "./header5";
import header6 from "./header6";

export default [callToAction1, callToAction2, callToAction3, callToAction4, callToAction5, callToAction11, callToAction6, callToAction7, callToAction8, callToAction9, callToAction10, content2, content3, content4, content5, content6, content7, content8, content9, content10, content1, content11, content12, content13, content14, content15, feature1, feature2, feature3, feature4, feature5, feature6, feature7, feature8, feature9, feature10, feature11, feature12, feature13, feature14, header1, header2, header3, header4, header5, header6];