approvedGitRepositories:
  - "https://github.com/webiny/webiny-upgrades-v6"

compressionLevel: mixed

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 2d
npmPreapprovedPackages:
  - "@webiny/di"
  - "@webiny/stdlib"
  - "wts-client"

yarnPath: .yarn/releases/yarn-4.14.1.cjs
