import { GraphQLSchemaModule } from "apollo-graphql";
import { CmsFieldTypePlugins } from "@webiny/api-headless-cms/types";

interface RenderTypesFromFieldPlugins {
    (params: { fieldTypePlugins: CmsFieldTypePlugins; type: string }): GraphQLSchemaModule[];
}

export const getSchemaFromFieldPlugins: RenderTypesFromFieldPlugins = ({
    fieldTypePlugins,
    type
}) => {
    return Object.values(fieldTypePlugins)
        .map(pl => {
            // Render gql types generated by field type plugins
            if (typeof pl[type].createSchema === "function") {
                return pl[type].createSchema();
            }
            return null;
        })
        .filter(Boolean);
};
