export * from "./ILoadingPresenter";
export * from "./ILoadingRepository";
export * from "./ISortPresenter";
export * from "./ISortRepository";
export * from "./ITrashBinDeleteEntryGateway";
export * from "./ITrashBinEntryMapper";
export * from "./ITrashBinListGateway";
export * from "./ITrashBinPresenter";
export * from "./ITrashBinRepository";
