export { default as UserTable } from "./user.mysql";
export { default as IdentityTable } from "./identity.mysql";
export { default as Identity2RoleTable } from "./identity2Role.mysql";
export { default as Identity2RoleGroupTable } from "./identity2RoleGroup.mysql";
export { default as RoleTable } from "./role.mysql";
export { default as RoleGroupTable } from "./roleGroup.mysql";
export { default as PermissionTable } from "./permission.mysql";
export { default as Role2RoleGroupTable } from "./role2RoleGroup.mysql";
export { default as Role2PermissionTable } from "./role2Permission.mysql";
