name: "\U0001F41B Bug report"
description: Create a report to help us improve
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue.
        Please fill in as much of the form below as you're able.
  - type: input
    attributes:
      label: Version
      description: Output of `yarn webiny --version`
  - type: input
    attributes:
      label: Operating System
  - type: input
    attributes:
      label: Browser
  - type: textarea
    attributes:
      label: What steps will reproduce the bug?
      description: Enter details about your bug.
  - type: textarea
    attributes:
      label: What is the expected behavior?
      description: If possible please provide textual output and/or screenshots.
  - type: textarea
    attributes:
      label: What do you see instead?
      description: If possible please provide textual output and/or screenshots.
  - type: textarea
    attributes:
      label: Additional information
      description: Tell us anything else you think we should know.
  - type: textarea
    attributes:
      label: Possible solution
      description: If you would like to suggest a fix/reason for the bug, please let us know.
