/**
 * --instructions / --manual
 *
 * Prints a clear, copy-paste-friendly guide for wiring up the Webiny MCP
 * server in any agent not covered by the built-in adapters.
 */

export function printInstructions(): void {
    const lines = [
        "",
        "╔══════════════════════════════════════════════════════════════════╗",
        "║           Webiny MCP Server — Manual Setup Guide                ║",
        "╚══════════════════════════════════════════════════════════════════╝",
        "",
        "The Webiny MCP server works with any agent that supports the Model",
        "Context Protocol (MCP) over stdio transport.",
        "",
        "── Step 1: Register the MCP server ───────────────────────────────",
        "",
        "Most agents accept a JSON config file. Add the following entry:",
        "",
        '  "webiny": {',
        '    "command": "npx",',
        '    "args": ["webiny", "mcp-server"]',
        "  }",
        "",
        "Where this config lives depends on your agent:",
        "",
        "  Agent              Config file",
        "  ─────────────────  ──────────────────────────────────────",
        "  Claude Code        .mcp.json                (project root)",
        "  Cursor             .cursor/mcp.json         (project root)",
        "  Windsurf           .windsurf/mcp.json       (project root)",
        "  Copilot/VS Code    .vscode/mcp.json         (note: uses 'servers', not 'mcpServers')",
        "  Cline              .vscode/cline_mcp_settings.json",
        "  Zed                ~/.config/zed/settings.json  (under 'context_servers')",
        "  Claude Desktop     ~/Library/Application Support/Claude/claude_desktop_config.json",
        "                     or %APPDATA%\\Claude\\claude_desktop_config.json  (Windows)",
        "",
        "Full example (the most common shape):",
        "",
        "  {",
        '    "mcpServers": {',
        '      "webiny": {',
        '        "command": "npx",',
        '        "args": ["webiny", "mcp-server"]',
        "      }",
        "    }",
        "  }",
        "",
        "── Step 2: Tell your agent about the MCP tools ───────────────────",
        "",
        "Add the following to your agent's instruction / rules file so it",
        "knows to reach for the Webiny tools automatically:",
        "",
        "  ## Webiny",
        "  This project uses the Webiny framework.",
        "  A `webiny` MCP server is available.",
        "  When helping with Webiny-related tasks:",
        "  1. Call `list_webiny_skills` to see available skills.",
        "  2. Call `get_webiny_skill` with the relevant topic before writing code.",
        "",
        "Where this instruction file lives:",
        "",
        "  Agent              Instruction file",
        "  ─────────────────  ──────────────────────────────────────",
        "  Claude Code        CLAUDE.md                (project root)",
        "  Cursor             .cursor/rules/*.mdc",
        "  Windsurf           .windsurf/rules/*.md",
        "  Copilot/VS Code    .github/copilot-instructions.md",
        "  Cline              system prompt in settings",
        "  Zed                system prompt in settings",
        "",
        "── Step 3: Verify the server starts ──────────────────────────────",
        "",
        "Test it with the MCP Inspector before relying on it in your agent:",
        "",
        "  npx @modelcontextprotocol/inspector npx webiny mcp-server",
        "",
        "Connect, click 'List Tools', and confirm you see:",
        "  • list_webiny_skills",
        "  • get_webiny_skill",
        "",
        "── Need a built-in adapter for your agent? ───────────────────────",
        "",
        "Open an issue or PR at: https://github.com/webiny/webiny-js",
        "The adapter just needs to write the right config file — see",
        "mcp/agents/claude.ts as a reference (~20 lines).",
        ""
    ];

    process.stdout.write(lines.join("\n") + "\n");
}
