name: Staging Branch - Push

on:
  push:
    branches: [staging]

# Ensures only one deployment to "staging" environment can be in progress at the same time.
concurrency: staging

jobs:
  build-test-deploy:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max_old_space_size=4096
      AWS_REGION: ${{ secrets.STAGING_AWS_REGION }}
      PULUMI_SECRETS_PROVIDER: ${{ secrets.STAGING_PULUMI_SECRETS_PROVIDER }}
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.STAGING_PULUMI_CONFIG_PASSPHRASE }}
      WEBINY_PULUMI_BACKEND: ${{ secrets.STAGING_WEBINY_PULUMI_BACKEND }}
      WEBINY_PROJECT_ID: ${{ secrets.STAGING_WEBINY_PROJECT_ID }}
      WEBINY_PROJECT_API_KEY: ${{ secrets.STAGING_WEBINY_PROJECT_API_KEY }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.STAGING_AWS_ROLE_ARN }}
          aws-region: ${{ secrets.STAGING_AWS_REGION }}
      - uses: actions/setup-node@v5
        with:
          node-version: 24

      - uses: actions/checkout@v5

      # Install and cache dependencies.
      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: .yarn/cache
          key: yarn-${{ hashFiles('**/yarn.lock') }}


      - name: Install dependencies
        run: yarn --immutable

      # Run static code analysis.
      - name: Check code formatting
        run: yarn format

      - name: Lint
        run: yarn lint

      - name: Deploy
        run: yarn webiny deploy --env staging

      # Add additional steps if needed. For example, if you have additional E2E
      # tests done with Cypress (https://www.cypress.io/), you can run them here.
