const SCHEDULE_MODEL_ID = "wbySchedule";
const SCHEDULE_ID_PREFIX = "wby-schedule-";
const SCHEDULE_MIN_FUTURE_SECONDS = 65;
const SCHEDULED_ACTION_EVENT_IDENTIFIER = "WebinyScheduledAction";
const SCHEDULED_ACTION_PUBLISH = "publish";
const SCHEDULED_ACTION_UNPUBLISH = "unpublish";
const SCHEDULED_ACTIONS = [
    SCHEDULED_ACTION_PUBLISH,
    SCHEDULED_ACTION_UNPUBLISH
];
export { SCHEDULED_ACTIONS, SCHEDULED_ACTION_EVENT_IDENTIFIER, SCHEDULED_ACTION_PUBLISH, SCHEDULED_ACTION_UNPUBLISH, SCHEDULE_ID_PREFIX, SCHEDULE_MIN_FUTURE_SECONDS, SCHEDULE_MODEL_ID };

//# sourceMappingURL=constants.js.map