export default `CREATE TABLE \`Completes\` (
	\`blob\` blob,
	\`char\` char,
	\`date\` date,
	\`dateTime\` datetime,
	\`decimal\` decimal,
	\`double\` double,
	\`enum\` enum,
	\`float\` float,
	\`int\` int,
	\`longBlob\` longblob,
	\`longText\` longtext,
	\`mediumBlob\` mediumblob,
	\`mediumInt\` mediumint,
	\`mediumText\` mediumtext,
	\`smallInt\` smallint,
	\`text\` text,
	\`time\` time,
	\`timestamp\` timestamp,
	\`tinyInt\` tinyint,
	\`tinyText\` tinytext,
	\`varChar\` varchar,
	\`year\` year,
	PRIMARY KEY (\`primary\`),
	KEY \`key\` (\`key\`),
	UNIQUE KEY \`unique\` (\`one\`, \`two\`, \`three\`, \`four\`),
	FULLTEXT KEY \`fullText\` (\`someSearchField\`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='Main Completes table...';`;
