/*
 * GENERATED FILE. Do not edit.
 *
 * Authored in `skills/shared/extensions/menu.md` and rendered here by
 * `scripts/generateExtensionContracts.mjs`. Run `yarn generate-skills` to regenerate.
 *
 * The same source also produces the MCP skill a developer gets, so guidance cannot drift between
 * writing an extension by hand and having the assistant write one.
 */
export const MENU_CONTRACT = "## What you are producing\n\nA menu entry here is stored configuration, not code. You supply the fields and the admin renders\nit; there is no component to write and nothing to import.\n\n- Pick a `name` nobody else is using. It is an identifier, so camelCase, no spaces.\n- `to` must be a path that already resolves. You are not creating the page. If the user is asking\n  for a destination that does not exist yet, say so rather than producing an item that leads\n  nowhere.\n- Use `parent` only for one of the groups listed above. A made-up parent hides the item completely.\n- Icons are not available here. A generated menu entry is text only.\n\n## What a menu entry is\n\nOne item in the admin's left sidebar. It is configuration, not a component: a name, the text to\nshow, where it links, and optionally which group it sits under.\n\nThe `name` is an identifier, not a label. It has to be unique across the whole sidebar, because it\nis also what other extensions use to place themselves relative to this one, and what `parent`\nrefers to when something nests under it.\n\n## Placement\n\n`parent` nests the item under an existing group. Omit it for a top-level entry. The groups that\nexist by default are:\n\n- `settings` and its subgroups `settings.system` and `settings.security`\n- `headlessCMS`\n- `wb` (Website Builder)\n- `dev-tools`\n\nNesting under a group that does not exist gives you an item nobody can see, and nothing reports it,\nso use one of the above or leave it top level.\n\n`pinnable` lets a user pin the item to the top of their sidebar. Most navigable destinations should\nset it; a group heading should not.\n\n## What a menu cannot do\n\nIt links to a route. It does not create one. If the path does not already resolve, the item appears\nand leads to a blank page, which is the usual way a new menu entry looks broken.";
