import type { CSSObject } from "@emotion/react";

// Supported HTML tags.
export type ListHtmlTag = "ol" | "ul";
export type HeadingHtmlTag = "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
export type ParagraphHtmlTag = "p";
export type QuoteBlockHtmlTag = "quoteblock";

export type TypographyHTMLTag = HeadingHtmlTag | ParagraphHtmlTag | ListHtmlTag | QuoteBlockHtmlTag;

export type TypographyValue = {
    css: CSSObject;
    id: string;
    tag: TypographyHTMLTag;
    name: string;
};

/*
 * Contains IDs of the styles and classes generated by Emotion.
 */
export type ThemeEmotionMap = {
    [styleId: string]: {
        id: string;
        tag: TypographyHTMLTag;
        name: string;
        styles: Record<string, any>;
        // emotion generated class
        className: string;
    };
};
