import type { CSSObject } from "@emotion/react";

export type TypographyValue = {
    id: string;
    tag: string;
    name: string;
    css?: CSSObject;
    className?: string;
};

/*
 * Contains IDs of the styles and classes generated by Emotion.
 */
export type ThemeEmotionMap = {
    [styleId: string]: {
        id: string;
        tag: string;
        name: string;
        styles?: Record<string, any>;
        // emotion generated class or user provided class
        className: string;
    };
};
