import { CmsFieldTypePlugins } from "@webiny/api-headless-cms/types";

interface RenderTypesFromFieldPlugins {
    (params: { fieldTypePlugins: CmsFieldTypePlugins; type: string }): string;
}

export const renderTypesFromFieldPlugins: RenderTypesFromFieldPlugins = ({
    fieldTypePlugins,
    type
}) => {
    return Object.values(fieldTypePlugins)
        .map(pl => {
            // Render gql types generated by field type plugins
            if (typeof pl[type].createTypes === "function") {
                return pl[type].createTypes();
            }
            return null;
        })
        .filter(Boolean)
        .join("\n");
};
