export const expectedFruitSchemaConfig = JSON.parse(
    JSON.stringify({
        query: "Query",
        mutation: "Mutation",
        types: [
            "CmsIdentity",
            "String",
            "CmsError",
            "CmsCursors",
            "CmsListMeta",
            "Boolean",
            "Int",
            "CmsDeleteEntryOptions",
            "CmsDeleteResponse",
            "CmsDeleteMultipleDataResponse",
            "ID",
            "CmsDeleteMultipleResponse",
            "CmsBooleanResponse",
            "WbyAcoLocation",
            "WbyAcoLocationInput",
            "WbyAcoLocationWhereInput",
            "SkipValidatorEnum",
            "CreateCmsEntryOptionsInput",
            "CreateRevisionCmsEntryOptionsInput",
            "UpdateCmsEntryOptionsInput",
            "CmsIdentityInput",
            "CmsEntryValidationResponseData",
            "CmsEntryValidationResponse",
            "CmsEntryStateType",
            "CmsEntryState",
            "ListWhereInputCmsEntryState",
            "CmsExportStructureResponse",
            "CmsImportStructureGroupInput",
            "CmsImportStructureModelInput",
            "CmsImportGroupStructureAction",
            "CmsImportModelStructureAction",
            "CmsImportStructureInput",
            "CmsImportValidateResponseDataGroupResultItem",
            "CmsImportValidateResponseDataGroupResult",
            "CmsImportValidateResponseDataModelResultItem",
            "CmsImportValidateResponseDataModelResult",
            "CmsImportValidateResponseData",
            "CmsImportValidateResponse",
            "CmsImportStructureResponseDataGroupResultItem",
            "CmsImportStructureResponseDataGroupResult",
            "CmsImportStructureResponseDataResultItem",
            "CmsImportStructureResponseDataModelResult",
            "CmsImportStructureResponseData",
            "CmsImportStructureResponse",
            "Query",
            "Mutation",
            "RevisionId",
            "JSON",
            "Long",
            "RefInput",
            "Number",
            "Any",
            "Date",
            "DateTime",
            "DateTimeZ",
            "Time",
            "CmsEntryStatusType",
            "CmsFieldValidation",
            "CmsFieldRenderer",
            "CmsPredefinedValue",
            "CmsPredefinedValues",
            "CmsContentModelField",
            "CmsContentModel",
            "CmsContentModelResponse",
            "CmsContentModelListResponse",
            "CmsPredefinedValueInput",
            "CmsPredefinedValuesInput",
            "CmsFieldRendererInput",
            "CmsFieldValidationInput",
            "CmsContentModelFieldInput",
            "CmsContentModelCreateInput",
            "CmsContentModelCreateFromInput",
            "CmsContentModelUpdateInput",
            "CmsModelMeta",
            "CmsPublishedContentEntry",
            "CmsContentEntry",
            "CmsContentEntriesResponse",
            "CmsContentEntryResponse",
            "CmsModelEntryInput",
            "CmsContentModelGroup",
            "CmsContentModelGroupInput",
            "CmsContentModelGroupResponse",
            "CmsContentModelGroupListResponse",
            "RefField",
            "RefFieldInput",
            "RefFieldWhereInput",
            "FruitApiModelValues",
            "FruitApiModel",
            "FruitApiModelMeta",
            "FruitApiModelInputValues",
            "FruitApiModelInput",
            "FruitApiModelGetWhereInputValues",
            "FruitApiModelGetWhereInput",
            "FruitApiModelListWhereInputValues",
            "FruitApiModelListWhereInput",
            "FruitApiModelResponse",
            "FruitApiModelMoveResponse",
            "FruitApiModelArrayResponse",
            "FruitApiModelListResponse",
            "FruitApiModelListSorter",
            "__Schema",
            "__Type",
            "__TypeKind",
            "__Field",
            "__InputValue",
            "__EnumValue",
            "__Directive",
            "__DirectiveLocation"
        ],
        directives: ["@include", "@skip", "@deprecated", "@specifiedBy", "@oneOf"],
        extensions: {},
        astNode: {
            kind: "SchemaDefinition",
            operationTypes: [
                {
                    kind: "OperationTypeDefinition",
                    type: {
                        kind: "NamedType",
                        name: { kind: "Name", value: "Query", loc: { start: 13699, end: 13704 } }
                    },
                    operation: "query"
                },
                {
                    kind: "OperationTypeDefinition",
                    type: {
                        kind: "NamedType",
                        name: { kind: "Name", value: "Mutation", loc: { start: 14559, end: 14567 } }
                    },
                    operation: "mutation"
                }
            ]
        },
        extensionASTNodes: [],
        assumeValid: false
    })
);
