export const expectedFruitSchema = JSON.parse(
    JSON.stringify({
        extensions: {},
        astNode: {
            kind: "SchemaDefinition",
            operationTypes: [
                {
                    kind: "OperationTypeDefinition",
                    type: {
                        kind: "NamedType",
                        name: { kind: "Name", value: "Query", loc: { start: 13699, end: 13704 } }
                    },
                    operation: "query"
                },
                {
                    kind: "OperationTypeDefinition",
                    type: {
                        kind: "NamedType",
                        name: { kind: "Name", value: "Mutation", loc: { start: 14559, end: 14567 } }
                    },
                    operation: "mutation"
                }
            ]
        },
        extensionASTNodes: [],
        _queryType: "Query",
        _mutationType: "Mutation",
        _directives: ["@include", "@skip", "@deprecated", "@specifiedBy", "@oneOf"],
        _typeMap: {
            CmsIdentity: "CmsIdentity",
            String: "String",
            CmsError: "CmsError",
            CmsCursors: "CmsCursors",
            CmsListMeta: "CmsListMeta",
            Boolean: "Boolean",
            Int: "Int",
            CmsDeleteEntryOptions: "CmsDeleteEntryOptions",
            CmsDeleteResponse: "CmsDeleteResponse",
            CmsDeleteMultipleDataResponse: "CmsDeleteMultipleDataResponse",
            ID: "ID",
            CmsDeleteMultipleResponse: "CmsDeleteMultipleResponse",
            CmsBooleanResponse: "CmsBooleanResponse",
            WbyAcoLocation: "WbyAcoLocation",
            WbyAcoLocationInput: "WbyAcoLocationInput",
            WbyAcoLocationWhereInput: "WbyAcoLocationWhereInput",
            SkipValidatorEnum: "SkipValidatorEnum",
            CreateCmsEntryOptionsInput: "CreateCmsEntryOptionsInput",
            CreateRevisionCmsEntryOptionsInput: "CreateRevisionCmsEntryOptionsInput",
            UpdateCmsEntryOptionsInput: "UpdateCmsEntryOptionsInput",
            CmsIdentityInput: "CmsIdentityInput",
            CmsEntryValidationResponseData: "CmsEntryValidationResponseData",
            CmsEntryValidationResponse: "CmsEntryValidationResponse",
            CmsEntrySystem: "CmsEntrySystem",
            ListWhereInputCmsEntrySystem: "ListWhereInputCmsEntrySystem",
            CmsExportStructureResponse: "CmsExportStructureResponse",
            CmsImportStructureGroupInput: "CmsImportStructureGroupInput",
            CmsImportStructureModelInput: "CmsImportStructureModelInput",
            CmsImportGroupStructureAction: "CmsImportGroupStructureAction",
            CmsImportModelStructureAction: "CmsImportModelStructureAction",
            CmsImportStructureInput: "CmsImportStructureInput",
            CmsImportValidateResponseDataGroupResultItem:
                "CmsImportValidateResponseDataGroupResultItem",
            CmsImportValidateResponseDataGroupResult: "CmsImportValidateResponseDataGroupResult",
            CmsImportValidateResponseDataModelResultItem:
                "CmsImportValidateResponseDataModelResultItem",
            CmsImportValidateResponseDataModelResult: "CmsImportValidateResponseDataModelResult",
            CmsImportValidateResponseData: "CmsImportValidateResponseData",
            CmsImportValidateResponse: "CmsImportValidateResponse",
            CmsImportStructureResponseDataGroupResultItem:
                "CmsImportStructureResponseDataGroupResultItem",
            CmsImportStructureResponseDataGroupResult: "CmsImportStructureResponseDataGroupResult",
            CmsImportStructureResponseDataResultItem: "CmsImportStructureResponseDataResultItem",
            CmsImportStructureResponseDataModelResult: "CmsImportStructureResponseDataModelResult",
            CmsImportStructureResponseData: "CmsImportStructureResponseData",
            CmsImportStructureResponse: "CmsImportStructureResponse",
            Query: "Query",
            Mutation: "Mutation",
            RevisionId: "RevisionId",
            JSON: "JSON",
            Long: "Long",
            RefInput: "RefInput",
            Number: "Number",
            Any: "Any",
            Date: "Date",
            DateTime: "DateTime",
            DateTimeZ: "DateTimeZ",
            Time: "Time",
            CmsEntryStatusType: "CmsEntryStatusType",
            CmsFieldValidation: "CmsFieldValidation",
            CmsFieldRenderer: "CmsFieldRenderer",
            CmsPredefinedValue: "CmsPredefinedValue",
            CmsPredefinedValues: "CmsPredefinedValues",
            CmsContentModelField: "CmsContentModelField",
            CmsContentModel: "CmsContentModel",
            CmsContentModelResponse: "CmsContentModelResponse",
            CmsContentModelListResponse: "CmsContentModelListResponse",
            CmsPredefinedValueInput: "CmsPredefinedValueInput",
            CmsPredefinedValuesInput: "CmsPredefinedValuesInput",
            CmsFieldRendererInput: "CmsFieldRendererInput",
            CmsFieldValidationInput: "CmsFieldValidationInput",
            CmsContentModelFieldInput: "CmsContentModelFieldInput",
            CmsContentModelCreateInput: "CmsContentModelCreateInput",
            CmsContentModelCreateFromInput: "CmsContentModelCreateFromInput",
            CmsContentModelUpdateInput: "CmsContentModelUpdateInput",
            CmsModelMeta: "CmsModelMeta",
            CmsPublishedContentEntry: "CmsPublishedContentEntry",
            CmsContentEntry: "CmsContentEntry",
            CmsContentEntriesResponse: "CmsContentEntriesResponse",
            CmsContentEntryResponse: "CmsContentEntryResponse",
            CmsModelEntryInput: "CmsModelEntryInput",
            CmsContentModelGroup: "CmsContentModelGroup",
            CmsContentModelGroupInput: "CmsContentModelGroupInput",
            CmsContentModelGroupResponse: "CmsContentModelGroupResponse",
            CmsContentModelGroupListResponse: "CmsContentModelGroupListResponse",
            RefField: "RefField",
            RefFieldInput: "RefFieldInput",
            RefFieldWhereInput: "RefFieldWhereInput",
            FruitApiModelValues: "FruitApiModelValues",
            FruitApiModel: "FruitApiModel",
            FruitApiModelMeta: "FruitApiModelMeta",
            FruitApiModelInputValues: "FruitApiModelInputValues",
            FruitApiModelInput: "FruitApiModelInput",
            FruitApiModelGetWhereInputValues: "FruitApiModelGetWhereInputValues",
            FruitApiModelGetWhereInput: "FruitApiModelGetWhereInput",
            FruitApiModelListWhereInputValues: "FruitApiModelListWhereInputValues",
            FruitApiModelListWhereInput: "FruitApiModelListWhereInput",
            FruitApiModelResponse: "FruitApiModelResponse",
            FruitApiModelMoveResponse: "FruitApiModelMoveResponse",
            FruitApiModelArrayResponse: "FruitApiModelArrayResponse",
            FruitApiModelListResponse: "FruitApiModelListResponse",
            FruitApiModelListSorter: "FruitApiModelListSorter",
            __Schema: "__Schema",
            __Type: "__Type",
            __TypeKind: "__TypeKind",
            __Field: "__Field",
            __InputValue: "__InputValue",
            __EnumValue: "__EnumValue",
            __Directive: "__Directive",
            __DirectiveLocation: "__DirectiveLocation"
        },
        _subTypeMap: {},
        _implementationsMap: {}
    })
);
