name: Greetings

on: [pull_request, issues, push]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello @${{ github.actor }} !  Welcome to Webiny! 💖, <br> Thank you and congrats 🎉 for opening your very first issue in this project. Hope you have a great time there! 🙂'
        pr-message: 'Hello @${{ github.actor }} ! Welcome to Webiny! 💖, <br> Thank you and congrats 🎉 for opening your pull request . We will get back to you as soon as we can.🙂 '
        push-message: 'Congrats on merging your pull request!🎉'
