name: Next Branch - Push

on:
  push:
    branches: [next]

env:
  NODE_OPTIONS: --max_old_space_size=4096

jobs:
  cache-dependencies-packages:
    name: Cache dependencies and packages
    runs-on: ubuntu-latest
    steps:
      - name: Get day of month (for caching purposes)
        id: day-of-month
        run: echo "::set-output name=day::$(node --eval "console.log(new Date().getDate())")"

      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: .yarn/cache
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/cache@v2
        id: cached-packages
        with:
          path: .webiny/cached-packages
          key: cached-packages-${{ runner.os }}-next-${{ steps.day-of-month.outputs.day }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true' || steps.cached-packages.outputs.cache-hit != 'true'
        run: yarn --immutable

      - name: Build packages
        if: steps.cached-packages.outputs.cache-hit != 'true'
        run: node scripts/buildWithCache.js

  code-analysis:
    needs: cache-dependencies-packages
    name: Static code analysis
    runs-on: ubuntu-latest
    steps:
      - name: Get day of month (for caching purposes)
        id: day-of-month
        run: echo "::set-output name=day::$(node --eval "console.log(new Date().getDate())")"

      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: .yarn/cache
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/cache@v2
        with:
          path: .webiny/cached-packages
          key: cached-packages-${{ runner.os }}-next-${{ steps.day-of-month.outputs.day }}

      - name: Install dependencies
        run: yarn --immutable

      - name: Check code formatting
        run: yarn prettier:check

      - name: Check dependencies
        run: yarn adio

      - name: Check TS configs
        run: yarn check-ts-configs

      - name: ESLint
        run: yarn eslint

  jest-tests:
    needs: cache-dependencies-packages
    name: Jest tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [12, 14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get day of month (for caching purposes)
        id: day-of-month
        run: echo "::set-output name=day::$(node --eval "console.log(new Date().getDate())")"

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: .yarn/cache
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn --immutable

      - uses: actions/cache@v2
        with:
          path: .webiny/cached-packages
          key: cached-packages-${{ runner.os }}-next-${{ steps.day-of-month.outputs.day }}

      - name: Build packages
        run: node scripts/buildWithCache.js

      - name: Run tests
        run: yarn test

  verdaccio-publish:
    needs: cache-dependencies-packages
    name: Publish to Verdaccio
    runs-on: ubuntu-latest
    steps:
      - name: Get day of month (for caching purposes)
        id: day-of-month
        run: echo "::set-output name=day::$(node --eval "console.log(new Date().getDate())")"

      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: .yarn/cache
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/cache@v2
        with:
          path: .webiny/cached-packages
          key: cached-packages-${{ runner.os }}-next-${{ steps.day-of-month.outputs.day }}

      - name: Install dependencies
        run: yarn --immutable

      - name: Build packages
        run: node scripts/buildWithCache.js

      - name: Start Verdaccio local server
        run: npx pm2 start verdaccio -- -c .verdaccio.yaml

      - name: Create ".npmrc" file in the project root, with a dummy auth token
        run: echo '//localhost:4873/:_authToken="dummy-auth-token"' > .npmrc

      - name: Configure NPM to use local registry
        run: npm config set registry http://localhost:4873

      - name: Set git email
        run: git config --global user.email "webiny-bot@webiny.com"

      - name: Set git username
        run: git config --global user.name "webiny-bot"

      - name: Version packages (no push, no changelog)
        run: yarn lerna:version:verdaccio

      - name: Release to Verdaccio
        run: yarn lerna:publish:verdaccio

      - name: Upload verdaccio files
        uses: actions/upload-artifact@v2
        with:
          name: verdaccio-files
          retention-days: 1
          path: |
            .verdaccio/
            .verdaccio.yaml

  test-create-webiny-project:
    needs: verdaccio-publish
    name: Test "create-webiny-project"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [12, 14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/download-artifact@v2
        with:
          name: verdaccio-files
          path: verdaccio-files

      - name: Start Verdaccio local server
        working-directory: verdaccio-files
        run: yarn add pm2 verdaccio && npx pm2 start verdaccio -- -c .verdaccio.yaml

      - name: Configure NPM to use local registry
        run: npm config set registry http://localhost:4873

      - name: Set git email (needed for create-webiny-project)
        run: git config --global user.email "webiny-bot@webiny.com"

      - name: Set git username (needed for create-webiny-project)
        run: git config --global user.name "webiny-bot"

      - name: Disable Webiny tracking
        run: mkdir ~/.webiny && echo '{id:"ci",tracking:false}' > ~/.webiny/config

      - name: Create a new Webiny project
        run: >
          npx create-webiny-project@beta test-project
          --tag beta --no-interactive
          --assign-to-yarnrc '{"npmRegistryServer":"http://localhost:4873","unsafeHttpWhitelist":["localhost"]}'
          --template-options '{"region":"eu-central-1","vpc":false}'

  deploy-preview:
    needs: cache-dependencies-packages
    name: Deploy preview
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PULUMI_SECRETS_PROVIDER: ${{ secrets.PULUMI_SECRETS_PROVIDER }}
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - uses: actions/download-artifact@v2
        with:
          name: verdaccio-files
          path: verdaccio-files

      - name: Start Verdaccio local server
        working-directory: verdaccio-files
        run: yarn add pm2 verdaccio && npx pm2 start verdaccio -- -c .verdaccio.yaml

      - name: Configure NPM to use local registry (for `npx create-webiny-project`)
        run: npm config set registry http://localhost:4873

      - name: Set git email (needed for create-webiny-project)
        run: git config --global user.email "webiny-bot@webiny.com"

      - name: Set git username (needed for create-webiny-project)
        run: git config --global user.name "webiny-bot"

      - name: Disable Webiny tracking
        run: mkdir ~/.webiny && echo '{id:"ci",tracking:false}' > ~/.webiny/config

      - name: Create a new Webiny project
        run: >
          npx create-webiny-project@beta test-project
          --tag beta --no-interactive
          --assign-to-yarnrc '{"npmRegistryServer":"http://localhost:4873","unsafeHttpWhitelist":["localhost"]}'
          --template-options '{"region":"eu-central-1","vpc":false,"iac":["pulumi",{"backend":{"url":"${{ secrets.AWS_PULUMI_S3_BUCKET_NEXT_BRANCH_PREVIEW }}"}}]}'

      - name: Print CLI version
        working-directory: test-project
        run: yarn webiny --version

      - name: Deploy preview
        working-directory: test-project
        run: yarn webiny deploy

      - name: Print project information
        working-directory: test-project
        run: yarn webiny info

      - name: Upload preview files
        uses: actions/upload-artifact@v2
        with:
          name: preview-files
          retention-days: 1
          path: |
            test-project/
            !test-project/node_modules/**/*
            !test-project/**/node_modules/**/*
            !test-project/.yarn/cache/**/*

  e2e-tests:
    needs: deploy-preview
    name: Run E2E (Cypress) tests
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-central-1
      PULUMI_SECRETS_PROVIDER: ${{ secrets.PULUMI_SECRETS_PROVIDER }}
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
    steps:
      - name: Get day of month (for caching purposes)
        id: day-of-month
        run: echo "::set-output name=day::$(node --eval "console.log(new Date().getDate())")"

      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: .yarn/cache
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/cache@v2
        with:
          path: .webiny/cached-packages
          key: cached-packages-${{ runner.os }}-next-${{ steps.day-of-month.outputs.day }}

      - name: Install dependencies
        run: yarn --immutable

      - name: Build packages
        run: yarn build

      - name: Setup - update Pulumi backend
        run: node scripts/setupPulumiBackend.js '${{ secrets.AWS_PULUMI_S3_BUCKET_NEXT_BRANCH_PREVIEW }}'

      - name: Setup - setup cypress.json config file
        run: node scripts/setupCypress.js --force

      - name: Cypress - run the rest of Admin app tests
        run: yarn cypress run --spec "cypress/integration/admin/**/*.spec.js"
