name: Pull Request Actions

on:
  pull_request_target:
    branches: [master]

env:
  NODE_OPTIONS: --max_old_space_size=4096
  MONGODB_SERVER: ${{ secrets.MONGODB_SERVER }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  WEBINY_TRACKING_PREFIX: ${{ secrets.WEBINY_TRACKING_PREFIX }}

jobs:
  initial-checks:
    name: Initial checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Check code formatting
        run: yarn prettier:check

      - name: Check dependencies
        run: yarn adio

  validate-commits:
    name: Validate commit messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webiny/action-conventional-commits@v1.0.2

  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build packages
        run: yarn build

      - name: Run tests
        run: yarn test

  build-e2e-test:
    name: Build and E2E test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Setup config files
        run: yarn setup-ci-cypress

      - name: Build packages
        run: yarn build

      - uses: webiny/action-post-run@1.0.0
        id: destroy-mongodb-database
        with:
          command: yarn setup-ci-cypress --post-run

      - uses: webiny/action-post-run@1.0.0
        id: webiny-remove-apps
        with:
          command: yarn webiny remove apps --env prod

      - uses: webiny/action-post-run@1.0.0
        id: webiny-remove-api
        with:
          command: yarn webiny remove api --env prod

      - name: Deploy API stack
        run: yarn webiny deploy api --env prod

      - name: Deploy Apps stack
        run: yarn webiny deploy apps --env prod

      - name: Setup Cypress config
        run: yarn setup-cypress

      - name: Wait for the website to be deployed
        run: node scripts/waitToDeploy

      - name: Cypress - run Admin app installation test
        run: yarn cypress run --spec "cypress/integration/adminInstallation/**/*.spec.js"

      - name: Cypress - run the rest of Admin app tests
        run: yarn cypress run --spec "cypress/integration/admin/**/*.spec.js"
