const { join } = require("path");
const { Component } = require("@serverless/core");

/**
 * This component needs to deploy:
 * - S3 bucket
 * - API GW for /graphql, /read, /upload
 */
class FilesComponent extends Component {
    async default(input = {}) {
        const { bucket = "webiny-files", ...rest } = input;
        const plugins = ["@webiny/api-files/plugins"];

        // Deploy graphql API
        const apolloService = await this.load("@webiny/serverless-apollo-service");
        const apolloOutput = await apolloService({ plugins, ...rest });

        // Create s3 bucket
        const s3 = await this.load("@serverless/aws-s3");
        const s3Output = s3({ name: bucket });

        // Deploy read/upload lambdas
        const lambda = await this.load("@serverless/function");
        const readFn = await lambda({
            timeout: 10,
            code: join(__dirname, "functions", "read"),
            handler: "handler.handler",
            description: "Read files",
            env: {
                BUCKET: s3Output.arn
            }
        });

        const uploadFn = await lambda({
            timeout: 10,
            code: join(__dirname, "functions", "upload"),
            handler: "handler.handler",
            description: "Upload files",
            env: {
                BUCKET: s3Output.arn
            }
        });

        // Update API Gateway generated by `apollo-service` component with new endpoints
        const apiGw = await this.load("@serverless/aws-api-gateway");
        const apiGwOutput = await apiGw({
            // Pass an `id` to update the existing API
            id: apolloOutput.api.id,
            endpoints: [
                ...apolloOutput.api.endpoints,
                { path: "/read", method: "ANY", function: readFn.arn },
                { path: "/upload", method: "ANY", function: uploadFn.arn }
            ]
        });

        // Output
        const output = {
            api: apiGwOutput,
            s3: s3Output,
            cdnOrigin: {
                url: apiGwOutput.url,
                pathPatterns: {
                    // potweakaj kako ti pase
                    "/read": {
                        ttl: 60
                    }
                }
            }
        };

        this.state.output = output;
        await this.save();

        return output;
    }

    async remove(input = {}) {
        // TODO: remove all created resources
    }
}

module.exports = FilesComponent;
